### PR TITLE
Add XPath filter

### PR DESCRIPTION
**Pull request by mrk-j**
Thank you for creating this package. I am using it in an application that crawls websites to feed them to an LLM. Sometimes I want to filter down the HTML to just a specific element or set of elements. I can implement this in my own code but thought this might be useful for everyone. 

I'm not sure what to think about warning suppression with `libxml_use_internal_errors`, but this was necessary to suppress warnings from loading the Laravel.com fixtures.

Please let me know what you think, I can also update the readme if you would consider merging this.

### CODE REVIEW

**Comment by stevebauman** [comment]
Hey @mrk-j! That's awesome, I'm glad you've found Hypertext useful!

I think this is a great feature. I've made some small adjustments to it and have added it to the readme.

Really appreciate your contribution 🙏

**Comment by stevebauman** [comment]
I've just released [v1.1.0](https://github.com/stevebauman/hypertext/releases/tag/v1.1.0) with this PR included. Run `composer update` and you're all set! 👍

**Comment by mrk-j** [comment]
Wow, that was fast! Thank you 💪

**Comment by stevebauman** [comment]
Happy to help @mrk-j! 🙏

**Pull request merged**
